//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TransactionType = &struct {
	Expense postgres.StringExpression
	Income  postgres.StringExpression
}{
	Expense: postgres.NewEnumValue("expense"),
	Income:  postgres.NewEnumValue("income"),
}
