// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/cativovo/budget-tracker/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// newMockuserStore creates a new instance of mockuserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserStore(t interface {
	mock.TestingT
	Cleanup(func())
},
) *mockuserStore {
	mock := &mockuserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserStore is an autogenerated mock type for the userStore type
type mockuserStore struct {
	mock.Mock
}

type mockuserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserStore) EXPECT() *mockuserStore_Expecter {
	return &mockuserStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockuserStore
func (_mock *mockuserStore) CreateUser(ctx context.Context, user model.User) (model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockuserStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *mockuserStore_Expecter) CreateUser(ctx interface{}, user interface{}) *mockuserStore_CreateUser_Call {
	return &mockuserStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *mockuserStore_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *mockuserStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_CreateUser_Call) Return(user1 model.User, err error) *mockuserStore_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *mockuserStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) (model.User, error)) *mockuserStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type mockuserStore
func (_mock *mockuserStore) GetUser(ctx context.Context, id string) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type mockuserStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockuserStore_Expecter) GetUser(ctx interface{}, id interface{}) *mockuserStore_GetUser_Call {
	return &mockuserStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *mockuserStore_GetUser_Call) Run(run func(ctx context.Context, id string)) *mockuserStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_GetUser_Call) Return(user model.User, err error) *mockuserStore_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserStore_GetUser_Call) RunAndReturn(run func(ctx context.Context, id string) (model.User, error)) *mockuserStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type mockuserStore
func (_mock *mockuserStore) UpdateUser(ctx context.Context, user model.User) (model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserStore_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type mockuserStore_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *mockuserStore_Expecter) UpdateUser(ctx interface{}, user interface{}) *mockuserStore_UpdateUser_Call {
	return &mockuserStore_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *mockuserStore_UpdateUser_Call) Run(run func(ctx context.Context, user model.User)) *mockuserStore_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserStore_UpdateUser_Call) Return(user1 model.User, err error) *mockuserStore_UpdateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *mockuserStore_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) (model.User, error)) *mockuserStore_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
