// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID   pgtype.UUID
	Name string
}

type Category struct {
	ID        pgtype.UUID
	Name      string
	Icon      string
	ColorHex  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	AccountID pgtype.UUID
}

type Transaction struct {
	ID              pgtype.UUID
	TransactionType int16
	Name            string
	Amount          decimal.Decimal
	Description     pgtype.Text
	Date            pgtype.Date
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	CategoryID      pgtype.UUID
	AccountID       pgtype.UUID
}
