//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TransactionType string

const (
	TransactionType_Expense TransactionType = "expense"
	TransactionType_Income  TransactionType = "income"
)

var TransactionTypeAllValues = []TransactionType{
	TransactionType_Expense,
	TransactionType_Income,
}

func (e *TransactionType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "expense":
		*e = TransactionType_Expense
	case "income":
		*e = TransactionType_Income
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TransactionType enum")
	}

	return nil
}

func (e TransactionType) String() string {
	return string(e)
}
