//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Transaction struct {
	ID              uuid.UUID `sql:"primary_key"`
	TransactionType TransactionType
	Name            string
	Amount          int64
	Description     *string
	Date            *time.Time
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	CategoryID      *uuid.UUID
	AccountID       uuid.UUID
}
